name: text_marquee
description: Text marquee is a widget for Flutter that scrolls text infinitely. You can customize the direction, style, and animation of the text.
version: 0.0.2
homepage: https://github.com/radnive/Flutter_TextMarquee

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
